service: csv-project

provider:
  name: aws
  runtime: python3.12
  stage: dev
  region: us-east-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: "arn:aws:s3:::my-trigger-bucket-csv-prsr/*"

functions:
  processUpload:
    handler: lambda_function.lambda_handler
    events:
      - s3:
          bucket: my-trigger-bucket-csv-prsr
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv