AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CsvProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Events:
        S3CsvUpload:
          Type: S3
          Properties:
            Bucket: myfirstcsvbucket
            Events: s3:ObjectCreated:*
            Filter:
              Suffix: .csv
  S3Bucket:
    Type: AWS::S3::Bucket
